task_name: FourRobotsStackCube
scene:
  name: Table
  primitives:
    - name: goal_region
      builder: mani_skill.utils.building.actors.build_red_white_target
      params:
        radius: 0.15
        thickness: 0.00005
        name: goal_region
        add_collision: False
        body_type: kinematic
        initial_pose:
          p: [0., 0., 0.001]

      pos:
        ppos:
          p: [0., -0.1, 0.001]
          q: [0., 1.5707963268, 0.]
        qpos: [0., 0.70710678, 0., 0.70710678]
        randp_scale: [0.02, 0.02, 0.]
        randq_scale: [0., 0., 0., 0.]

    - name: cubeA
      builder: mani_skill.utils.building.actors.build_cube
      params:
        half_size: 0.02
        color: [0.2, 0.6, 1.0, 1.]
        name: cubeA
        initial_pose:
          p: [0., 0., 0.025]

      pos:
        ppos:
          p: [0.3, 1.2, 0.025]
        qpos: [1., 0., 0., 0.]
        randp_scale: [0.05, -0.05, 0.]
        randq_scale: [0., 0., 0., 0.]
        random_quaternions: [1, 1, 0]

    - name: cubeB
      builder: mani_skill.utils.building.actors.build_cube
      params:
        half_size: 0.02
        color: [1.0, 0.2, 0.2, 1.]
        name: cubeB
        initial_pose:
          p: [0., 0.3, 0.02]

      pos:
        ppos:
          p: [-0.3, 1.2, 0.02]
        qpos: [1., 0., 0., 0.]
        randp_scale: [0.05, 0.05, 0.]
        randq_scale: [0., 0., 0., 0.]
        random_quaternions: [1, 1, 0]

  assets: 
    - name: table
      file_path: assets/scenes/table/table.glb
      collision:
        type: box
        pos:
          p: [0, 0, 0.45982145]
          half_size: [3.0225, 1.51125, 0.45982145]
      pos: 
        ppos:
          p: [-0.1, 0., -0.9196429]
          q: [0., 0., 1.5707963268]
        randp_scale: [0., 0., 0.]
        randq_scale: [0., 0., 0., 0.]
      scale: [4.375, 4.375, 1.75]
  env:
    floor_width: 100

agents:
  - robot_uid: panda-0
    pos:
      ppos:
        p: [0.8, 1, 0.]
        q: [0., 0., 3.1415926536]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]

  - robot_uid: panda-1
    pos:
      ppos:
        p: [-0.8, 1, 0.]
        q: [0., 0., 0.]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]

  - robot_uid: panda-2
    pos:
      ppos:
        p: [0.65, -0., 0.]
        q: [0., 0., 3.1415926536]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]

  - robot_uid: panda-3
    pos:
      ppos:
        p: [-0.65, -0., 0.]
        q: [0., 0., 0.]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]

cameras:
  sensor:
    - 
      uid: head_camera_agent0
      pose:
        type: pose
        params: [[-0.0350691, 1.78102, 0.604382], [0.639904, 0.272547, 0.260446, -0.669633]]
      width: 320
      height: 240
      fov: 1.3
      near: 0.01
      far: 10

    - 
      uid: head_camera_agent1
      pose:
        type: pose
        params: [[-0.0350691, 1.78102, 0.604382], [0.639904, 0.272547, 0.260446, -0.669633]]
      width: 320
      height: 240
      fov: 1.3
      near: 0.01
      far: 10

    - 
      uid: head_camera_agent2
      pose:
        type: pose
        params: [[1.01761, 0.393484, 0.68599], [0.00699133, -0.293124, 0.00212842, 0.956047]]
      width: 320
      height: 240
      fov: 1.3
      near: 0.01
      far: 10

    - 
      uid: head_camera_agent3
      pose:
        type: pose
        params: [[-0.812075, 0.386323, 0.719128], [0.921695, 0.0204127, 0.384268, -0.0489947]]
      width: 320
      height: 240
      fov: 1.3
      near: 0.01
      far: 10

    - 
      uid: head_camera_global
      pose:
        type: look_at
        params: [[0., 0.8, 1.0], [0., 0.8, 0.1]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.01
      far: 10
  
  human_render:
    - 
      uid: render_camera
      pose:
        type: look_at
        params: [[2.0, 2.0, 1.0], [0.0, 0.0, 0.1]]
      width: 512
      height: 512
      fov: 1.2
      near: 0.01
      far: 100 