task_name: ThreeRobotsPlaceShoes
scene:
  name: Table
  env:
    floor_width: 100
  assets: 
    - name: table
      file_path: assets/scenes/table/table.glb
      collision:
        type: box
        pos:
          p: [0, 0, 0.45982145]
          half_size: [3.0225, 1.51125, 0.45982145]
      pos: 
        ppos:
          p: [-0.12, 0., -0.9196429]
          q: [0., 0., 1.5707963268]
        randp_scale: [0., 0., 0.]
        randq_scale: [0., 0., 0., 0.]
      scale: [4.375, 4.375, 1.75]
    
objects:
  -
    name: shoe_left
    file_path: assets/objects/single_shoe_annotated/base.glb
    annotation_path: assets/objects/single_shoe_annotated/model_data.json
    material: 
      type: sapien.pysapien.physx.PhysxMaterial
      params:
        static_friction: 0.3
        dynamic_friction: 0.3
        restitution: 0.
    visual:
      filename: assets/objects/single_shoe_annotated/base.glb
      scale: [0.1, 0.1, 0.1]
    collision:
      type: convex
      filename: assets/objects/single_shoe_annotated/base.glb
      scale: [0.1, 0.1, 0.1]
    pos:
      ppos:
        p: [-0.6, -0.2, 0.042]
      qpos: [0.495, 0.498, 0.503, 0.505]
      randp_scale: [0.12, 0.12, 0.]
      randq_scale: [0., 0., 0., 0.]
    mass_params:
      mass: 0.5
      cmass_local_pose: [0., 0., 0.]
      inertia: [0.1, 0.1, 0.1]

  -
    name: shoe_right
    file_path: assets/objects/single_shoe_annotated/base.glb
    annotation_path: assets/objects/single_shoe_annotated/model_data.json
    material: 
      type: sapien.pysapien.physx.PhysxMaterial
      params:
        static_friction: 0.3
        dynamic_friction: 0.3
        restitution: 0.
    visual:
      filename: assets/objects/single_shoe_annotated/base.glb
      scale: [0.1, 0.1, 0.1]
    collision:
      type: convex
      filename: assets/objects/single_shoe_annotated/base.glb
      scale: [0.1, 0.1, 0.1]
    pos:
      ppos:
        p: [-0.6, 0.2, 0.042]
      qpos: [0.495, 0.498, 0.503, 0.505]
      randp_scale: [0.12, 0.12, 0.]
      randq_scale: [0., 0., 0., 0.]
    mass_params:
      mass: 0.5
      cmass_local_pose: [0., 0., 0.]
      inertia: [0.1, 0.1, 0.1]

  -
    name: shoe_box
    file_path: assets/objects/box/mobility.urdf
    annotation_path: assets/objects/box/model_data.json
    scale: [0.3, 0.3, 0.25]
    qpos: [1., 1., 3., 1.]
    pos:
      ppos:
        p: [-0.1, -0.025, 0.13]
      qpos: [1., 0., 0., 0.]
      randp_scale: [0.05, 0.05, 0.]
      randq_scale: [0., 0., 0., 0.]
      
agents:
  -
    robot_uid: panda-0
    pos:
      ppos:
        p: [-0.65, -0.55, 0.]
        q: [0., 0., 0.]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]
  -
    robot_uid: panda-1
    pos:
      ppos:
        p: [-0.65, 0.6, 0.]
        q: [0., 0., 0.]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]
  -
    robot_uid: panda-2
    pos:
      ppos:
        p: [1., 0., 0.]
        q: [0., 0., -3.1415926536]
      qpos: [0., 0.3926990817, 0.1, -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]

cameras:
  sensor:
    - 
      uid: head_camera_agent0
      pose:
        type: pose
        params: [[1.4, 0.8, 0.75], [0.225318, 0.190302, 0.0449241, -0.954463]]
      width: 320
      height: 240
      fov: 1.06
      near: 0.1
      far: 10
    - 
      uid: head_camera_agent1
      pose:
        type: pose
        params: [[0.0307903, -0.260513, 0.96955], [0.355388, -0.442111, 0.196488, 0.799769]]
      width: 320
      height: 240
      fov: 1.57
      near: 0.1
      far: 10
    - 
      uid: head_camera_agent2
      pose:
        type: pose
        params: [[-0.289462, -0.0428455, 1.21524], [0.857709, -4.61936e-05, 0.514136, 0.00011766]]
      width: 320
      height: 240
      fov: 1.57
      near: 0.1
      far: 10
    - 
      uid: head_camera_global
      pose:
        type: pose
        params: [[-0.247516, -0.171751, 1.7], [0.710879, 0.00694868, 0.703245, -0.00702344]]
      width: 320
      height: 240
      fov: 1.57
      near: 0.1
      far: 10
  human_render:
    - uid: render_camera
      pose:
        type: look_at
        params: [[1.4, 0.8, 0.75], [0.0, 0.1, 0.1]]
      width: 320
      height: 240
      fov: 1.2
      near: 0.01
      far: 100