from .place_food import PlaceFoodEnv
from .place_cube_in_cup import PlaceCubeInCupEnv
from .three_robots_stack_cube import ThreeRobotsStackCubeEnv
from .take_photo import TakePhotoEnv
from .long_pipeline_delivery import LongPipelineDeliveryEnv
from .strike_cube_hard import StrikeCubeHardEnv
from .three_robots_place_shoes import ThreeRobotsPlaceShoesEnv
from .four_robots_stack_cube import FourRobotsStackCubeEnv